# Copyright 2026 yu-iskw
#
# Licensed under the Apache License, Version 2.0 (the "License");
name: Trunk Check

on:
  pull_request: {} # yamllint disable-line empty-values
  workflow_dispatch: {} # yamllint disable-line empty-values

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
